### ISSUE TITLE
Import pdf & pdf output option

### ISSUE THREAD

**Issue by ThedChristensen** [scantailor/scantailor#116] opened 2014-09-27 22:35 UTC
I'm new to Scan Tailor (ST) and I really like the program - amazing what it can do and I think it can be very useful at my work place, a law firm, where we handle a lot of scanned documents/literature. However, there is a practical "problem" in that all the files we have are in pdf-format and that it's quite cumbersome to first convert the files into jpg-format, edit them in ST, and then convert them back to pdf. This is a problem as there is a lot pdfs and many - non-computer-wise - people handling them.

Hence, it would really have an impact if you could just import pdf-files directly to ST (in the best of worlds, by drag-and-drop) and also if you, as an output option, could choose a compiled pdf-file. Then people would not have to spend a lot of time converting and merging the image files (making sure they have chosen the right files), using another program.

Anyway, it seems to be a great tool - and thanks for all the efforts in creating and enhancing it!

Best regards,
Thomas, Copenhagen

**Comment by tuxor1337** [comment] 2015-03-24 16:16
Yes, this is obviously a duplicate of #48

**Closed** 2015-03-25 17:17 UTC
Labels: duplicate
