### ISSUE TITLE
Better Split Pages

### ISSUE THREAD

**Issue by okrick** [scantailor/scantailor#226] opened 2016-08-23 02:26 UTC
The pages in the book were in three columns with a header and footer for each page.  I ran Split pages but none of the pages automatically split probably because of the full width header and footer.  I then selected the first page and manually split on the first column.  Then Clicked Change-->Manual Mode & All Pages.  Let the program run the remaining pages automatically but all of the remaining pages were split at the extreme right hand position just after where the header and footer stopped.

I can see the problem with the software trying to find a path through the header and footer barriers.  However, could the search on the remaining pages be limited to +- say 10% of the split position in the current page?  Alternatively limit the path search to the middle 80% or so vertically of the documents to eliminate the headers and footers from giving erroneous results.
[1035.zip](https://github.com/scantailor/scantailor/files/431567/1035.zip)

**Comment by atla5** [comment] 2016-08-28 16:31
A bit of a duplicate of #221. 

I marked it as this upcoming release though. 

thanks for the issue!

**Closed by atla5** 2016-08-28 16:31 UTC
Labels: bug, duplicate, enhancement, split pages, [priority] medium
